### ISSUE TITLE
how to run on jupyter/  google colab?

### ISSUE THREAD

**Issue by jinpengchina** [streamlit/demo-uber-nyc-pickups#1]
how to run on jupyter/  google colab?

**Comment by monchier** [comment]
Thanks for your interest, Streamlit is a python library that you can use
when coding in an IDE. It currently doesn't work inside Jupyter or CoLab.

Matteo

**Comment by jonherke** [comment]
bummer

**Comment by amir1m** [comment]
This might help: 
https://discuss.streamlit.io/t/free-streamlit-dev-environment-through-colaboratory/2778/4
