### ISSUE TITLE
Demo is broken

### ISSUE THREAD

**Issue by arjun-krishna1** [streamlit/demo-uber-nyc-pickups#26]
- `AttributeError: This app has encountered an error. The original error message is redacted to prevent data leaks.`
![image](https://user-images.githubusercontent.com/45014214/194719067-2f6235de-6be7-4eae-9d10-2c641071f3a1.png)

**Comment by blackary** [comment]
Thanks for the heads-up! This was because of a change in the pydeck library, and has now been resolved.
