### ISSUE TITLE
Replace st.experimental_get_query_params with st.query_params

### ISSUE THREAD

**Issue by araderberg** [streamlit/demo-uber-nyc-pickups#36]
I received the following warnings:
Please replace st.experimental_get_query_params with st.query_params.

st.experimental_get_query_params will be removed after 2024-04-11.

Refer to our [docs page](https://docs.streamlit.io/library/api-reference/utilities/st.query_params) for more information.

**Comment by sowmyamanojna** [comment]
I raised a PR to fix this: [PR 37](https://github.com/streamlit/demo-uber-nyc-pickups/pull/37). 
You can go over the changes made to overcome the warning.

**Comment by araderberg** [comment]
Hi there,

@sowmyamanojna  my program is about NY city collisions and not uber drivers. I checked my code and could not locate st.experimental_get_query_params unless I missed something. Thanks for letting me know.
